task2
Kottans/chernivtsi-frontend-2017 pull request #20
Opened 2017-11-14 21:48 UTC by duchevich

2017-11-17 19:01 UTC, denis-zavgorodny requested changes

2017-11-17 19:01 UTC, denis-zavgorodny commented on homeworks/es6-basics/duchevich/homework.js
> +    this.qnt = 1
Объекту товара лучше не знать о своем количестве

2017-11-17 19:01 UTC, denis-zavgorodny commented on homeworks/es6-basics/duchevich/homework.js
> +UserCart.prototype = new Cart;
Можно связывать прототипы `UserCart.prototype` и `Cart.prototype`

2017-11-17 19:01 UTC, denis-zavgorodny commented on homeworks/es6-basics/duchevich/homework.js
> +UserCart.prototype = new Cart;
без создания отдельного объекта типа `Cart `

2017-11-17 19:55 UTC, duchevich commented on homeworks/es6-basics/duchevich/homework.js
> +    this.qnt = 1
исправила

2017-11-20 14:33 UTC, denysdovhan approved these changes
Great job!

2017-11-20 14:33 UTC, denysdovhan commented on homeworks/es6-continued/duchevich/promisify.js
> +  function newFunc(url){
You can do `return function newFunc() {`

2017-11-20 14:33 UTC, denysdovhan commented on homeworks/es6-continued/duchevich/promisify.js
> +    const promise  = new Promise((resolve, reject) => {
Here the same `return new Promise((resolve, reject) => {`

2017-11-20 14:33 UTC, denysdovhan commented on homeworks/es6-continued/duchevich/promisify.js
> +          return reject(error.message);
Better to return `error` object as is.

2017-11-20 14:34 UTC, merged