homework es6_basics by Andriy Shilov
Kottans/chernivtsi-frontend-2017 pull request #21
Opened 2017-11-15 10:58 UTC by endrushilov

2017-11-17 19:00 UTC, denis-zavgorodny requested changes

2017-11-17 19:00 UTC, denis-zavgorodny commented on homeworks/es6-basics/endrushilov/script.js
> +    this.amount = function(){
методы лучше выносить в прототип

2017-11-17 19:00 UTC, denis-zavgorodny commented on homeworks/es6-basics/endrushilov/script.js
> +        for(var j = 1; j < count; j++){
А если изначально в корзине 5 товаров и нужно оставить 3?

2017-11-20 14:35 UTC, denysdovhan requested changes
Please, fix your sollution

2017-11-21 19:58 UTC, denysdovhan approved these changes

2017-11-24 19:09 UTC, denis-zavgorodny approved these changes

2017-12-18 20:28 UTC, merged