💗🐱💗
Kottans/chernivtsi-frontend-2017 pull request #22
Opened 2017-11-15 13:42 UTC by wildbananastiia

2017-11-17 18:57 UTC, denis-zavgorodny requested changes

2017-11-17 18:57 UTC, denis-zavgorodny commented on homeworks/es6-basics/wildbananastiia/script.js
> +function Item(id, name, quantity) {
`new Item(1, 'Chair', 2000)`
третьим параметром в функциою передается цена товара

2017-11-20 14:35 UTC, denysdovhan approved these changes
Neat solution with fibonacci 👍

2017-11-20 14:36 UTC, merged

2017-11-20 22:32 UTC, denis-zavgorodny commented on homeworks/es6-basics/wildbananastiia/script.js
> +UserCart.prototype = Object.create(Cart.prototype);
Зачем так сложно? Можно просто `UserCart.prototype = Cart.prototype;`

2017-11-20 22:32 UTC, denis-zavgorodny commented on homeworks/es6-basics/wildbananastiia/script.js
> +            item.price *= quantity;
А если несколько раз вызвать. Например, updateQnt(3), а потом на уменьшение updateQnt(2)?