bagmetv es6-basics files
Kottans/chernivtsi-frontend-2017 pull request #23
Opened 2017-11-15 14:30 UTC by bagmetv

2017-11-17 18:46 UTC, denis-zavgorodny requested changes

2017-11-17 18:46 UTC, denis-zavgorodny commented on homeworks/es6-basics/bagmetv/main.js
> +UserCart.prototype = new Cart ();
Зачем создавать отдельно объект, можно просто связать прототипы `UserCart.prototype` и `Cart.prototype`

2017-11-17 18:46 UTC, denis-zavgorodny commented on homeworks/es6-basics/bagmetv/main.js
> +    // updateQnt
Метод не реализован

2017-11-20 14:36 UTC, denysdovhan requested changes
Please, fix your solution!

2017-11-20 21:40 UTC, denis-zavgorodny commented on homeworks/es6-basics/bagmetv/main.js
> +UserCart.prototype = new Cart ();
`UserCart.prototype = Cart.prototype` можно просто связать прототипы, не обязательно создавать новый объект

2017-11-21 20:00 UTC, denysdovhan requested changes
Why did you delete `README`? `.DS_Store` should be ignored

2017-11-21 20:00 UTC, denysdovhan commented on homeworks/es6-basics/bagmetv/.jshintrc
> +{
drop this file

2017-11-21 21:32 UTC, bagmetv commented
Hi! Sorry, my fault. Please specify how to resolve those conflicting files.

2017-11-22 17:12 UTC, maxkharena commented
You should resolve git conflict 
"how to" links:
https://githowto.com/resolving_conflicts
https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/
http://gitready.com/advanced/2009/02/25/keep-either-file-in-merge-conflicts.html

2018-01-11 19:35 UTC, denysdovhan commented
We close this PR since it's not completed, conflict still not resolved and a deadline was expired.

2018-01-11 19:35 UTC, closed without merging