Add es6 hw
Kottans/chernivtsi-frontend-2017 pull request #24
Opened 2017-11-15 14:34 UTC by lenanyasha

2017-11-17 18:43 UTC, denis-zavgorodny requested changes

2017-11-17 18:43 UTC, denis-zavgorodny commented on homeworks/es6-basics/lenanyasha/cart.js
> +UserCart.prototype = Object.create(Cart.prototype);
Зачем создавать промежуточный объект через `Object.create`. Можно просто связать прототипы `Cart.prototype` и `UserCart.prototype`

2017-11-17 18:43 UTC, denis-zavgorodny commented on homeworks/es6-basics/lenanyasha/cart.js
> +    this.qnt = 1;
Товар не должен знать о своем количестве

2017-11-18 20:06 UTC, lenanyasha commented on homeworks/es6-basics/lenanyasha/cart.js
> +    this.qnt = 1;
Если нельзя создать дополнительное поле `this.qnt`, можно в методе `updateQnt` умножить цену на количество товара, но тогда `updateQnt` будет работать корректно всего один раз. Могу ли я сделать поле `price` сделать объектом, внутри с оригинальной ценой и текущей? Есть еще вариант в массив пушить один и тот же товар несколько раз . Например, если обновить количество товара с `id === 1` до 10, то в массиве будет 10 объектов:
```
{
  id: 1,
  price,
  name,
}
```

Какой из этих двух способов мне использовать? Или если есть лучше - feel free to share, please

2017-11-20 14:37 UTC, denysdovhan commented on homeworks/es6-basics/lenanyasha/cart.js
> +    this.qnt = 1;
@denis-zavgorodny your answer?

2017-11-20 21:46 UTC, denis-zavgorodny commented on homeworks/es6-basics/lenanyasha/cart.js
> +    this.qnt = 1;
корзина из 10 объектов вполне себе решение. Если мы ограничены структурой корзины. Не удобно с ними работать будет при изменении количества. Но в рамках таких ограничений - можно

2017-11-22 19:42 UTC, closed without merging