yuracr9
Kottans/chernivtsi-frontend-2017 pull request #25
Opened 2017-11-15 14:37 UTC by yuracr9

2017-11-16 12:10 UTC, denis-zavgorodny requested changes

2017-11-16 12:10 UTC, denis-zavgorodny commented on homeworks/es6-basics/yuracr9/es6_basics_hw.js
> +UserCart.prototype = new Cart();
Прототип UserCart можно связать с прототипом Cart Не нужно создавать для этого новый объект.

2017-11-16 12:10 UTC, denis-zavgorodny commented on homeworks/es6-basics/yuracr9/es6_basics_hw.js
> +  for (let i = 0; i < amount - 1; i++) {
Зачем хранить все экземпляры одного объекта товара?

2017-11-20 14:38 UTC, denysdovhan approved these changes

2017-11-20 14:38 UTC, merged

2017-11-20 22:17 UTC, denis-zavgorodny commented on homeworks/es6-basics/yuracr9/es6_basics_hw.js
> +  this.amount = amount;
Это должна быть цена товара

2017-11-20 22:17 UTC, denis-zavgorodny commented on homeworks/es6-basics/yuracr9/es6_basics_hw.js
> +    if (this.goods[i].id == id) this.goods[i].amount *= amount;
цену товара менять нельзя У одной единицы товара она не меняется