ES6-basics homework
Kottans/chernivtsi-frontend-2017 pull request #26
Opened 2017-11-15 15:33 UTC by IrenKomar

2017-11-15 16:11 UTC, denis-zavgorodny commented on homeworks/es6-basics/IrenKomar/card.js
> +    this.amount = function () {
Методы лучше выносить в прототип

2017-11-15 16:11 UTC, denis-zavgorodny commented on homeworks/es6-basics/IrenKomar/card.js
> +    this.__proto__ = cartParent;
Прототип можно указать у конструктора через 
`UserCart.prototype`

2017-11-16 11:01 UTC, denysdovhan requested changes

2017-11-16 11:01 UTC, denysdovhan commented on homeworks/es6-basics/IrenKomar/card.js
> +function Item(id, name, price, count = 1) {
ES6 default params. Not sure if it's okay in one line with es5 code 🤔

2017-11-16 11:01 UTC, denysdovhan commented on homeworks/es6-basics/IrenKomar/card.js
>          for(var i = 0; i < this.goods.length; i++)
Please, fix indentation.

2017-11-16 11:58 UTC, denis-zavgorodny commented on homeworks/es6-basics/IrenKomar/card.js
> +function Item(id, name, price, count = 1) {
Вообще, count – это свойство относится к количеству товара в корзине, а не к объекту товара. Т.е. сам Item – это всегда один товар. Если товара в корзине три, то это три объекта Item.

2017-11-20 14:23 UTC, denysdovhan approved these changes

2017-11-20 14:23 UTC, merged

2017-11-20 22:38 UTC, denis-zavgorodny commented on homeworks/es6-basics/IrenKomar/card.js
>  UserCart.prototype = cartParent;
МОжно просто связать `UserCart.prototype = Cart.prototype`

2017-11-20 22:38 UTC, denis-zavgorodny commented on homeworks/es6-basics/IrenKomar/card.js
> +            this.add(new Item(newId, name, price));
Близкое решение. Но, что будет если вызвать метод дважды?
updateQnt(4), а затем updateQnt(2)?