Task2. User Basket
Kottans/chernivtsi-frontend-2017 pull request #27
Opened 2017-11-15 15:53 UTC by tkachdmytro

2017-11-15 16:15 UTC, denis-zavgorodny commented on homeworks/es6-basics/tkachdmytro/js/script.js
> +    this.remove = function (item_index) {
Методы лучше выносить в прототип

2017-11-15 16:15 UTC, denis-zavgorodny commented on homeworks/es6-basics/tkachdmytro/js/script.js
> +UserCart.prototype = new Cart();
Лучше связать прототип UserCart с прототипом Cart

2017-11-15 16:16 UTC, denis-zavgorodny commented on homeworks/es6-basics/tkachdmytro/js/script.js
> +        var result = this.goods.reduce(function(sum, current) {
Зачем здесь промежуточная переменная?

2017-11-20 14:39 UTC, denysdovhan requested changes
Please, fix your solution!

2017-11-20 14:39 UTC, denysdovhan commented on homeworks/es6-basics/tkachdmytro/index.html
> +<!DOCTYPE html >
There is no need in `index.html`. You can run this file with `Node.js` or [jsbin](http://jsbin.com)

2017-11-24 00:06 UTC, tkachdmytro commented on homeworks/es6-basics/tkachdmytro/index.html
> +<!DOCTYPE html >
забрав

2017-11-24 18:42 UTC, denis-zavgorodny approved these changes

2017-12-18 21:05 UTC, denysdovhan approved these changes

2017-12-18 21:05 UTC, merged