task2 - ES6
Kottans/chernivtsi-frontend-2017 pull request #28
Opened 2017-11-15 16:22 UTC by EvgeniyaP

task2 - ES6

2017-11-16 11:55 UTC, denis-zavgorodny commented on homeworks/es6-basics/EvgeniyaP/main.js
> +	this.qnt = 1;
Объект товара всегда один, он не несет информации о количестве товаров в корзине

2017-11-16 11:55 UTC, denis-zavgorodny commented on homeworks/es6-basics/EvgeniyaP/main.js
> +	this.amount = function () {
Методы лучше выносить в прототип. а не хранить их в каждом созданном объекте

2017-11-16 11:55 UTC, denis-zavgorodny commented on homeworks/es6-basics/EvgeniyaP/main.js
> +UserCart.prototype = new Cart();
Можно просто связать прототип новой корзины с прототипом старой, ведь нужный метод add хранится у `Cart.prototype`

2017-11-20 14:40 UTC, denysdovhan requested changes
Please, fix your solution!

2017-11-20 14:40 UTC, denysdovhan commented on homeworks/es6-basics/EvgeniyaP/main.html
> +<!DOCTYPE html>
There is no need in `index.html`. You can run this with Node.js or [jsbin](http://jsbin.com)

2017-11-23 19:45 UTC, denis-zavgorodny requested changes

2017-11-23 19:45 UTC, denis-zavgorodny commented on homeworks/es6-basics/EvgeniyaP/main.js
> +UserCart.prototype.updateQnt = function(idNum, qnt) {
а если будет два вызова
`updateQnt(3)` и `updateQnt(2)`, то результирующее колиество товара должно быть 2. А по коду это не так.

Корзина – это массив элементов-объектов Item Соответственно, метод updateQnt должен управлять размером массива `goods `

2017-11-24 18:48 UTC, denis-zavgorodny approved these changes

2017-11-25 13:49 UTC, denysdovhan approved these changes

2017-11-25 13:49 UTC, merged