homework task2
Kottans/chernivtsi-frontend-2017 pull request #30
Opened 2017-11-16 21:23 UTC by irkin-cv

2017-11-17 18:40 UTC, denis-zavgorodny requested changes

2017-11-17 18:40 UTC, denis-zavgorodny commented on homeworks/es6-basics/irkin-cv/main.js
> +    this.qnt = 1;
Товар не должен знать о своем количестве

2017-11-17 18:40 UTC, denis-zavgorodny commented on homeworks/es6-basics/irkin-cv/main.js
> +UserCart.prototype = new Cart();
Зачем создавать объект? Можно просто связать прототипы `UserCart.prototype` и `Cart.prototype`

2017-11-17 19:16 UTC, irkin-cv commented on homeworks/es6-basics/irkin-cv/main.js
> +UserCart.prototype = new Cart();
вот так? 
UserCart.prototype = Cart.prototype;

2017-11-17 19:19 UTC, irkin-cv commented on homeworks/es6-basics/irkin-cv/main.js
> +    this.qnt = 1;
а какой, тогда, объект должен хранить количество? (Cart или UserCart тогда получается?)

2017-11-20 22:39 UTC, denis-zavgorodny commented on homeworks/es6-basics/irkin-cv/main.js
> +    this.qnt = 1;
В данном случае – никакой. Корзина – это просто массив объектов типа Cart

2017-11-20 22:39 UTC, denis-zavgorodny commented on homeworks/es6-basics/irkin-cv/main.js
> +UserCart.prototype = new Cart();
Да

2017-11-24 19:03 UTC, denis-zavgorodny approved these changes

2017-12-18 20:29 UTC, merged