es6-basics AllaSydoriak
Kottans/chernivtsi-frontend-2017 pull request #31
Opened 2017-11-16 22:14 UTC by AllaSydoriak

2017-11-17 18:39 UTC, denis-zavgorodny requested changes

2017-11-17 18:39 UTC, denis-zavgorodny commented on homeworks/es6-basics/AllaSydoriak/es6-basics.js
> +UserCart.prototype = Object.create(Cart.prototype);
`UserCart.prototype` можно просто связать с `Cart.prototype` Зачем делать еще один объект через `Object.create`?

2017-11-17 18:39 UTC, denis-zavgorodny commented on homeworks/es6-basics/AllaSydoriak/es6-basics.js
> +  this.quontity = 1;
Товар не должен знать о своем количестве. Количество товара это свойство в корзине.

2017-11-17 19:46 UTC, AllaSydoriak commented on homeworks/es6-basics/AllaSydoriak/es6-basics.js
> +UserCart.prototype = Object.create(Cart.prototype);
поправлю) у мене просто з самого початку чомусь не виходило так зробити.

2017-11-17 19:49 UTC, AllaSydoriak commented on homeworks/es6-basics/AllaSydoriak/es6-basics.js
> +  this.quontity = 1;
Тобто в UserCart?

2017-11-20 14:26 UTC, denysdovhan commented
@denis-zavgorodny please, review changes for `es6-basics`. @komarnitskyi you have to check `es6-continued`.

2017-11-20 22:36 UTC, denis-zavgorodny requested changes

2017-11-20 22:36 UTC, denis-zavgorodny commented on homeworks/es6-basics/AllaSydoriak/es6-basics.js
> +            item.price *= quontity;
А если вызвать несколько раз updateQnt(3), а потом updateQnt(1)? Количество товаров должно быть 1, а по коду выходит что 3

2017-11-24 18:48 UTC, denis-zavgorodny requested changes

2017-11-24 18:48 UTC, denis-zavgorodny commented on homeworks/es6-basics/AllaSydoriak/es6-basics.js
> +            this.goods.pop(items[0]);
Array.pop удаляет последний элемент в массиве. А если нужно удалить 3 по счету элемент?

2017-12-18 21:09 UTC, denysdovhan approved these changes

2017-12-18 21:09 UTC, merged