classes and fibonachi es6 continued
Kottans/chernivtsi-frontend-2017 pull request #39
Opened 2017-11-22 10:53 UTC by endrushilov

2017-11-23 20:54 UTC, komarnitskyi requested changes

2017-11-23 20:54 UTC, komarnitskyi commented on homeworks/es6-continued/endrushilov/cart_classes.js
> +             var new_elements = [].fill.call({length: count_this_elem}, Object.assign(this_elem));
You shouldn't declare new variables inside an `if` statement

2017-11-23 20:54 UTC, komarnitskyi commented on homeworks/es6-continued/endrushilov/cart_classes.js
> +function Cart () {}
`Cart` should be declared using classes syntax

2017-11-23 20:54 UTC, komarnitskyi commented on homeworks/es6-continued/endrushilov/cart_classes.js
> +        for(var i = 0; i < this.goods.length; i++){
Please, try to do this calculation using `reduce`

2017-11-30 11:57 UTC, denysdovhan commented
@komarnitskyi please, check again

2017-12-18 21:26 UTC, merged