Add es6-continued
Kottans/chernivtsi-frontend-2017 pull request #43
Opened 2017-11-22 22:07 UTC by lenanyasha

2017-11-23 07:43 UTC, komarnitskyi requested changes

2017-11-23 07:43 UTC, komarnitskyi commented on homeworks/es6-continued/lenanyasha/cart.js
> +    getAll() {
Please, remove duplicated method

2017-11-23 07:43 UTC, komarnitskyi commented on homeworks/es6-continued/lenanyasha/cart.js
> +function Cart () {}
Cart should be declared as a class

2017-11-30 11:59 UTC, denysdovhan commented
@komarnitskyi please, review this homework again

2017-12-15 21:05 UTC, komarnitskyi approved these changes

2017-12-15 21:05 UTC, merged