webapi
Kottans/chernivtsi-frontend-2017 pull request #54
Opened 2017-11-25 20:16 UTC by okedo

2017-11-30 12:12 UTC, denysdovhan commented
@denis-zavgorodny review, please.

2017-12-10 19:50 UTC, denis-zavgorodny requested changes

2017-12-10 19:50 UTC, denis-zavgorodny commented on homeworks/browser-api/okedo/testXHR.js
> +function getXHR() {
Не реализована возможность кеширования данных на стороне клиента

2017-12-18 21:29 UTC, denysdovhan commented
@okedo please, fix your PR.

2018-01-11 19:36 UTC, denis-zavgorodny commented
Не до конца реализован функционал

2018-01-11 19:36 UTC, closed without merging