browser-api homework
Kottans/chernivtsi-frontend-2017 pull request #55
Opened 2017-11-26 09:45 UTC by IrenKomar

2017-11-30 12:13 UTC, denysdovhan commented
@denis-zavgorodny please, review.

2017-12-10 19:49 UTC, denis-zavgorodny requested changes

2017-12-10 19:49 UTC, denis-zavgorodny commented on homeworks/browser-api/IrenKomar/script.js
> +var xhr = new XMLHttpRequest();
xhr зачем глобально вынесена? Лучше инкапсулировать логику работы с сетью и данными в рамках метода get. А данные возвращать через promise, например

2017-12-18 21:25 UTC, denis-zavgorodny commented on homeworks/browser-api/IrenKomar/script.js
> +var xhr = new XMLHttpRequest();
@IrenKomar

2018-01-11 19:37 UTC, merged