browser api homework
Kottans/chernivtsi-frontend-2017 pull request #58
Opened 2017-11-27 10:58 UTC by endrushilov

2017-11-30 12:17 UTC, denysdovhan commented
@denis-zavgorodny review, please.

2017-12-10 19:47 UTC, denis-zavgorodny requested changes

2017-12-10 19:47 UTC, denis-zavgorodny commented on homeworks/browser-api/endrushilov/task.js
> +var xhr = new XMLHttpRequest();
Глобально не стоит переменную пробрасывать. Лучше инкаппсулировать логику работы с xhr внутри функции get. А результат возвращать через promise

2017-12-18 21:24 UTC, denis-zavgorodny requested changes
Добработай реквест

2018-01-11 19:35 UTC, merged