react-basic
Kottans/chernivtsi-frontend-2017 pull request #65
Opened 2017-12-01 20:31 UTC by yuracr9

2017-12-04 01:39 UTC, kostyandrew commented on homeworks/react-basic/yuracr9/src/App.js
> +  getData() {
Краще використовувати componentWillMount

2017-12-04 01:40 UTC, kostyandrew commented on homeworks/react-basic/yuracr9/src/App.js
> +        this.state.data.push(response);
`this.state` не можна змінювати напряму.

2017-12-04 01:43 UTC, kostyandrew commented on homeworks/react-basic/yuracr9/src/App.js
> +    this.getData();
це викликало подвійний запит за файлом. зміна стейту викликала рендер який викликав `this.getData` вдруге.

2017-12-04 01:46 UTC, kostyandrew commented on homeworks/react-basic/yuracr9/src/TreeView.js
> +      style = {display: "none"};
замість інлайн стилів використай https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator

2017-12-04 01:47 UTC, kostyandrew commented on homeworks/react-basic/yuracr9/src/TreeView.js
> +      visible: true
за замовчуванням пункти мають бути закриті

2017-12-04 01:48 UTC, kostyandrew requested changes
Також треба слідкувти за помилками в консолі

2017-12-13 23:38 UTC, kostyandrew commented
досі помилки з ключами. `Warning: Each child in an array or iterator should have a unique "key" prop.`
ще попередження про зайвий імпорт лого і відсутність `alt` у `img`

2017-12-18 21:33 UTC, denysdovhan approved these changes
@yuracr9 LGTM, but fix issue with `key`s.

2018-01-11 19:39 UTC, merged