React basic homework <3
Kottans/chernivtsi-frontend-2017 pull request #67
Opened 2017-12-09 16:20 UTC by wildbananastiia

2017-12-10 20:19 UTC, kostyandrew commented on homeworks/react-basic/wildbananastiia/tree-view/src/App.js
> +class Folder extends Component {
Винести компоненти в окремі файли

2017-12-10 20:20 UTC, kostyandrew commented on homeworks/react-basic/wildbananastiia/tree-view/src/App.js
> +    this.state = { isDisplayChild: true };
папки мають бути закриті спочатку

2017-12-10 20:23 UTC, kostyandrew requested changes
крім того, саме завдання має знаходитись одразу в директорії з вашим нікомЖ, як в попередніх

2017-12-18 21:42 UTC, kostyandrew commented
@wildbananastiia `fixed review remarks`  коміт зачіпає дуже багато файлів і видаляє чужі домашки

2018-01-11 19:58 UTC, denysdovhan commented
This PR is already merged manually.

2018-01-11 19:58 UTC, closed without merging