React basic
Kottans/chernivtsi-frontend-2017 pull request #73
Opened 2017-12-16 22:44 UTC by AllaSydoriak

2017-12-17 22:08 UTC, kostyandrew commented on homeworks/browser-api/AllaSydoriak/build/schedule.js
> +var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false;
зайвий коміт

2017-12-17 22:10 UTC, kostyandrew commented on homeworks/react-basic/AllaSydoriak/react-basic/src/App.js
> +        <Folder name={this.state.data.type} data={this.state.data}></Folder>
`JSX` елементи без контенту краще прописувати як одинарні `<Folder />`

2017-12-17 22:12 UTC, kostyandrew commented on homeworks/react-basic/AllaSydoriak/react-basic/src/File.js
> +import '../node_modules/font-awesome/css/font-awesome.min.css';
цей імпорт варто робити в корні проекту і не через відносні шляхи до нод модулів. краще `font-awesome/css/font-awesome.min.css`

2017-12-17 22:13 UTC, kostyandrew requested changes
також зайві зміни з іншої домашки в цій вітці

2017-12-17 22:26 UTC, kostyandrew commented
ще треба пофіксити структуру файлів. домашка має розміщуватись одразу в папці з ніком

2017-12-18 12:57 UTC, kostyandrew commented
```
./src/App.js
  Line 2:  'logo' is defined but never used  no-unused-vars
  Line 5:  'File' is defined but never used  no-unused-vars
```

2017-12-18 21:34 UTC, denysdovhan approved these changes
Good, but fix linter issues.

2017-12-18 21:34 UTC, merged